#ifndef VKLEARNIN_DESCRIPTORS_PEROBJECTDESCRIPTORS_HPP
#define VKLEARNIN_DESCRIPTORS_PEROBJECTDESCRIPTORS_HPP

class PerObjectDescriptors {

};

#endif // VKLEARNIN_DESCRIPTORS_PEROBJECTDESCRIPTORS_HPP